# .github/workflows/main.yml

name: Custom JavaScript Action

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: turbostart-npm
      uses: clutchd/turbostart-npm@v3.0.1
          

    - name: Run JavaScript action
      uses: ./custom-javascript
      with:
        name: 'Punit'
